"""empty message

Revision ID: 9762ab5475a5
Revises: 
Create Date: 2026-08-07 04:40:12.876978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9762ab5475a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('posted')

    # ### end Alembic commands ###
